# Elixir baby!
language: 'elixir'

elixir: 1.8.1
otp_release: 21.2.6

# Make sure PostgreSQL is running
addons:
  postgresql: 9.6

# Use the cache to build faster
cache:
  directories:
    - _build
    - deps
    - assets/node_modules
    - priv/plts

# Set global environment variables
env:
  global:
    - MIX_ENV: test
    - DATABASE_URL: postgres://localhost/elixir_boilerplate_test

# Output Travis server IP for debugging
before_install:
  - echo `curl --verbose http://jsonip.com`

# Install the node version we need, install the node packages,
# create the database and prepare the application
before_script:
  - nvm install 10.14.2
  - nvm use 10.14.2
  - npm install -g npm@6.4.1
  - npm --prefix assets install
  - mix compile
  - mix ecto.create
  - mix ecto.migrate

script:
  - ./priv/scripts/ci-check.sh
