# Use Travis container-based infrastructure
sudo: false

# Elixir baby!
language: 'elixir'

elixir: 1.6.4
otp_release: 20.2.1

# Make sure PostgreSQL is running
addons:
  postgresql: 9.6


# Use the cache to build faster
cache:
  directories:
    - _build
    - deps
    - assets/node_modules

# Set global environment variables
env:
  global:
    - PORT: 3000
    - CANONICAL_HOST: 'test.local'
    - MIX_ENV: 'test'
    - SECRET_KEY_BASE: 'lolwut'
    - DATABASE_URL: 'postgres://localhost/phoenix_boilerplate_test'

# Output Travis server IP for debugging
before_install:
  - 'echo `curl --verbose http://jsonip.com`'

# Install the node version we need, install the node packages,
# create the database and prepare the application
before_script:
  - nvm install 10.4.1
  - nvm use 10.4.1
  - npm install -g npm@6.1.0
  - npm --prefix assets install
  - mix compile
  - mix ecto.create
  - mix ecto.migrate

script:
  - ./priv/scripts/ci-check.sh
