version: '3.3'
services:
  application:
    image: phoenix_boilerplate
    container_name: phoenix_boilerplate
    environment:
      - CANNONICAL_HOST=localhost
      - FORCE_SSL=false
      - PORT=4000
      - SESSION_KEY=phoenix_boilerplate_session
      - SECRET_KEY_BASE=md7okHvbfCImL1Y8UBMCHUANaY6Vmnlj36diu62/yZmMC5Rbz55FC3RZj3aLUQe1
      - SIGNING_SALT=_add_a_little_salt_here_
      - DEBUG_ERRORS=false
      - ERLANG_COOKIE=x39mN8c47NPvfKVLXVELLPsNWI10NrE9E3CcpgNhdQx0KGS0R7y2omO53gy8QO/V
      - DATABASE_URL=postgres://postgres:development@postgres/phoenix_boilerplate_dev
      - DATABASE_POOL_SIZE=20
      - DATABASE_SSL=false
    ports:
      - 4000:4000
    depends_on:
      - postgres
  postgresql:
    image: postgres:10.3
    container_name: phoenix_boilerplate-postgres
    environment:
      - POSTGRES_DB=phoenix_boilerplate_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - phoenix_boilerplate_psql:/var/lib/postgresql/data
volumes:
  phoenix_boilerplate_psql:
